### ISSUE TITLE
Cant install on Mac 10.13.4 

### ISSUE THREAD

**Issue by greentornado** [vapor/homebrew-tap#18]
It reports

```
Warning: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/vapor/homebrew-tap/vapor.rb:7:in `<class:Vapor>'
Please report this to the vapor/tap tap!

Warning: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/vapor/homebrew-tap/vapor.rb:8:in `<class:Vapor>'
Please report this to the vapor/tap tap!

Warning: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/vapor/homebrew-tap/ctls.rb:10:in `<class:Ctls>'
Please report this to the vapor/tap tap!

Warning: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/vapor/homebrew-tap/ctls.rb:11:in `<class:Ctls>'
Please report this to the vapor/tap tap!
```

**Comment by 0xTim** [comment]
@greentornado that should just be a warning and shouldn't stop the installation, are there are errors in the logs? (The warnings have been fixed and will be released soon)

**Comment by 0xTim** [comment]
Closing due to inactivity
